version: '3.6'

services:

  space-cloud:
    image: spaceuptech/space-cloud
    restart: always
    ports:
    - "4122:4122"
    - "4126:4126"
    environment:
      DEV: "false"
      ADMIN_USER: "admin"
      ADMIN_PASS: "senha123"
      ADMIN_SECRET: "some-secret"
      #CONFIG: /config/config.yaml
    volumes:
      - space_data:/storage
      # /path/to/config.yaml:/config/config.yaml
    networks:
     - backend

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "senha123"
    volumes:
      - db_data:/var/lib/postgresql/data 
    networks:
      - backend
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "jarzamendia@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "senha123"
    ports:  
      - "16543:80"
    networks:
      - backend

volumes:
  db_data:
  space_data:

networks:
  backend: